// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CrearCheque(arg1) {
  return window['go']['main']['App']['CrearCheque'](arg1);
}

export function CrearChequeDevuelto(arg1) {
  return window['go']['main']['App']['CrearChequeDevuelto'](arg1);
}

export function CrearCliente(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CrearCliente'](arg1, arg2, arg3, arg4);
}

export function CrearMovimientoCabinet(arg1) {
  return window['go']['main']['App']['CrearMovimientoCabinet'](arg1);
}

export function ExportCabinetsExcel() {
  return window['go']['main']['App']['ExportCabinetsExcel']();
}

export function ExportChequesExcel() {
  return window['go']['main']['App']['ExportChequesExcel']();
}

export function GetCheques() {
  return window['go']['main']['App']['GetCheques']();
}

export function GetChequesDevueltos() {
  return window['go']['main']['App']['GetChequesDevueltos']();
}

export function GetClienteByRut(arg1) {
  return window['go']['main']['App']['GetClienteByRut'](arg1);
}

export function GetClientes() {
  return window['go']['main']['App']['GetClientes']();
}

export function GetEstados() {
  return window['go']['main']['App']['GetEstados']();
}

export function GetMorosos() {
  return window['go']['main']['App']['GetMorosos']();
}

export function GetMovimientosCabinets() {
  return window['go']['main']['App']['GetMovimientosCabinets']();
}

export function GetServerTime() {
  return window['go']['main']['App']['GetServerTime']();
}

export function GetVendedores() {
  return window['go']['main']['App']['GetVendedores']();
}

export function ResolveOrCreateCliente(arg1, arg2) {
  return window['go']['main']['App']['ResolveOrCreateCliente'](arg1, arg2);
}

export function SoftDeleteCheque(arg1) {
  return window['go']['main']['App']['SoftDeleteCheque'](arg1);
}

export function SoftDeleteChequeDevuelto(arg1) {
  return window['go']['main']['App']['SoftDeleteChequeDevuelto'](arg1);
}

export function SoftDeleteMovimientoCabinet(arg1) {
  return window['go']['main']['App']['SoftDeleteMovimientoCabinet'](arg1);
}

export function UpdateCheque(arg1, arg2) {
  return window['go']['main']['App']['UpdateCheque'](arg1, arg2);
}

export function UpdateChequeDevuelto(arg1, arg2) {
  return window['go']['main']['App']['UpdateChequeDevuelto'](arg1, arg2);
}

export function UpdateEstadoCheque(arg1, arg2) {
  return window['go']['main']['App']['UpdateEstadoCheque'](arg1, arg2);
}

export function UpdateMovimientoCabinet(arg1, arg2) {
  return window['go']['main']['App']['UpdateMovimientoCabinet'](arg1, arg2);
}
