// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CrearCheque(arg1:main.ChequeInput):Promise<void>;

export function CrearChequeDevuelto(arg1:main.ChequeDevueltoInput):Promise<void>;

export function CrearCliente(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function ExportCheques():Promise<Array<main.ExportRow>>;

export function GetCheques():Promise<Array<main.Cheque>>;

export function GetChequesDevueltos():Promise<Array<main.ChequeDevuelto>>;

export function GetClienteByRut(arg1:string):Promise<main.Cliente>;

export function GetClientes():Promise<Array<main.Cliente>>;

export function GetEstados():Promise<Array<main.EstadoCheque>>;

export function GetMorosos():Promise<Array<main.ClienteMoroso>>;

export function GetServerTime():Promise<string>;

export function GetVendedores():Promise<Array<main.Vendedor>>;

export function ResolveOrCreateCliente(arg1:string,arg2:string):Promise<string>;

export function SoftDeleteCheque(arg1:number):Promise<void>;

export function SoftDeleteChequeDevuelto(arg1:number):Promise<void>;

export function UpdateCheque(arg1:number,arg2:main.ChequeInput):Promise<void>;

export function UpdateChequeDevuelto(arg1:number,arg2:main.ChequeDevueltoInput):Promise<void>;

export function UpdateEstadoCheque(arg1:number,arg2:number):Promise<void>;
